<?php

require_once ('Setup/Common/EmailGenerator.php');

class EmailGeneratorTest extends PHPUnit_Framework_TestCase {

	private $__generator;

	public function setUp() {
		$this->__generator = new EmailGenerator();
	}

	public function testGenerate_WhenCalled_GeneratesValidEmail() {
		$generatedEmail = $this->__generator->generate();
		// The regex below is not strictly correct, but will check the e-mail
		// generated is valid (the regex will incorrectly fail some vaild e-mails,
		// but none that should be generated by the above code).
		$this->assertEquals(1, preg_match('/\b[A-Za-z0-9]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\b/', $generatedEmail));
	}
}