INSERT INTO `hms_meta` (`name`, `value`) VALUES
('member_box_cost', '-500'),
('member_box_individual_limit', '3'),
('member_box_limit', '129'),
('label_printer_ip', 'localhost'),
('so_accountNumber', '19098596'),
('so_sortCode', '60-24-77'),
('so_accountName', 'Nottinghack'),
('members_guide_html', 'http://guide.nottinghack.org.uk'),
('members_guide_pdf', 'http://readthedocs.org/projects/nottingham-hackspace-members-guide/downloads/pdf/latest/'),
('rules_html', 'http://rules.nottinghack.org.uk'),
('access_street_door', '1234'),
('access_inner_door', '1234'),
('access_wifi_ssid', 'HSNOTTS'),
('access_wifi_password', '123456'),
('membership_email', 'membership@localhost'),
('link_Resources Requests', 'https://docs.google.com/forms/d/1jURztPXwFxh3NbXU0oqdC7T3YfJYK-6x67lq79HAqR8/viewform'),
('link_Broken Tools', 'https://goo.gl/zXpof6'),
('link_Induction', 'https://goo.gl/Jl59IM'),
('link_Members Guide', 'http://guide.nottinghack.org.uk'),
('link_Hackspace Rules', 'http://rules.nottinghack.org.uk')
;