INSERT INTO `hms_meta` (`name`, `value`) VALUES
('member_box_cost', '-500'),
('member_box_individual_limit', '3'),
('member_box_limit', '129'),
('label_printer_ip', 'localhost'),
('so_accountNumber', '19098596'),
('so_sortCode', '60-24-77'),
('so_accountName', 'Nottinghack'),
('members_guide_html', 'http://guide.nottinghack.org.uk'),
('members_guide_pdf', 'http://readthedocs.org/projects/nottingham-hackspace-members-guide/downloads/pdf/latest/'),
('rules_html', 'http://rules.nottinghack.org.uk'),
('access_street_door', '1234'),
('access_inner_door', '1234'),
('access_wifi_ssid', 'HSNOTTS'),
('access_wifi_password', '123456'),
('membership_email', 'membership@localhost'),
('bank_csv_folder', '/vagrant/app/tmp/csv'),
('audit_revoke_interval' , 'P2M'),
('audit_warn_interval', 'P1M14D')
;